#PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
